### ISSUE TITLE
Adding all customers sites under their own reseller id

### ISSUE THREAD

**Issue by cwispy** [cwispy/ispcfg3#1]
Determine how to have multiple sites for the same customer in WHMCS setup in ISPConfig under a single reseller code so the client does not require multiple logins to manage their websites.

**Comment by dmgeurts** [comment]
Testing things I notice that a client in whmcs becomes a client in ispconfig which is really not what I want from ispc - whmcs integration at all... This code could do with some better documentation tbh.

**Comment by cwispy** [comment]
Its called open source for a reason. I could have kept it to myself so everyone had to start from scratch every time they wanted to integrate whmcs - ispconfig, but I decided to put it up for others to take and "modify" to suit their own needs! Are you volunteering to write the better documentation? Being open, means just that, it is open. If you want world class documentation and support, then find someone to write and document the software for you and PAY them for it.

**Comment by dmgeurts** [comment]
True, very true. Sorry for my tone, and thank you for making this available for free. Found the related thread on Sourceforge so will have a good read of that and then see how I can contribute to the code.

The 3.1 code includes hooks.php and elfinder.connector.php, what do these do?
