### ISSUE TITLE
Error DNS Teamplate Creation

### ISSUE THREAD

**Issue by simonfr** [cwispy/ispcfg3#10]
Hello,
I'm getting a SOAP error when I'm trying to add DNS zone:
```
[Tue Dec 15 18:07:17.982586 2015] [fcgid:warn] [pid 7958] [client 141.101.64.83:47568] mod_fcgid: stderr: PHP Warning:  include(/usr/local/ispconfig/interface/lib/lang/.lng): failed to open stream: No such file or directory in /usr/local/ispconfig/interface/lib/classes/tform.inc.php on line 134
[Tue Dec 15 18:07:17.982726 2015] [fcgid:warn] [pid 7958] [client 141.101.64.83:47568] mod_fcgid: stderr: PHP Warning:  include(): Failed opening '/usr/local/ispconfig/interface/lib/lang/.lng' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /usr/local/ispconfig/interface/lib/classes/tform.inc.php on line 134
[Tue Dec 15 18:07:17.982755 2015] [fcgid:warn] [pid 7958] [client 141.101.64.83:47568] mod_fcgid: stderr: PHP Warning:  include(lib/lang/en_dns_soa.lng): failed to open stream: No such file or directory in /usr/local/ispconfig/interface/lib/classes/tform.inc.php on line 141
[Tue Dec 15 18:07:17.982777 2015] [fcgid:warn] [pid 7958] [client 141.101.64.83:47568] mod_fcgid: stderr: PHP Warning:  include(): Failed opening 'lib/lang/en_dns_soa.lng' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /usr/local/ispconfig/interface/lib/classes/tform.inc.php on line 141
[Tue Dec 15 18:07:18.016035 2015] [fcgid:warn] [pid 4553] (104)Connection reset by peer: [client 141.101.64.83:45778] mod_fcgid: error reading data from FastCGI server
[Tue Dec 15 18:07:18.016178 2015] [core:error] [pid 4553] [client 141.101.64.83:45778] End of script output before headers: index.php
```
Any idea how resolve this ?
Thank you

**Comment by cwispy** [comment]
include(/usr/local/ispconfig/interface/lib/lang/.lng)

Looks like you do not have your Language set correctly.

**Comment by simonfr** [comment]
I've checked and re-checked but nothing. Here : https://www.howtoforge.com/community/threads/new-ispconfig-module-for-whmcs.67824/page-12#post-334327 you say there is something to do with translation. You now what we need to do ?

**Comment by cwispy** [comment]
The error you posted shows that your ISPConfig is looking for the .lng where it should be loading something like en.lng or fr.lng etc. What I am saying is the problem looks like its to do with your ispconfig install, and not the whmcs module.

**Comment by alexxwire** [comment]
Hi guys, sorry for hijacking the post but I'm having the same issue? simonfr - did you manage to fix the problem?
Thanks

**Comment by simonfr** [comment]
No. But if you want to help me to found a solution, or found a solution, I'm here.

**Comment by alexxwire** [comment]
Sure, I'll give it a go. The only thing I have different from a standard ispconfig setup is florian's DKIM patch.

I can't say for certain but I think the problems started after upgrading from wheezy to Jessie? I'll study the logs properly tomorrow.

**Comment by alexxwire** [comment]
Just had another thought, I'll try hard coding the language in the ispconfig form that's being requested as .lng doesn't exist anyway?

**Comment by alexxwire** [comment]
cwispy - any chance I can have a copy of your tform.inc.php file? ours seem to be looking in the wrong directories.

Thanks,
Alex

**Comment by simonfr** [comment]
Yes :
[tform.inc.php.txt](https://github.com/cwispy/ispcfg3/files/93533/tform.inc.php.txt)

(I've change .php to .php.txt because .php not supported by github)

**Comment by cwispy** [comment]
I have posted a comment in the thread on HowtoForge about this error being related to php5-cgi crashing on Debian Jessie.

**Comment by simonfr** [comment]
Hi, any issue ?
