### ISSUE TITLE
WHMCS 6.2

### ISSUE THREAD

**Issue by sandro-saperfare** [cwispy/ispcfg3#11]
Hi Cwispy, is the new version of WHMCS compatibly with your module?
After update from 6.1.1 to 6.2 there are problems communicating with ispconfig.
The error is: Could not connect to host.

The error log say:
[Wed Jan 20 14:05:50 2016] [error] [client x.x.x.x] PHP Warning:  Invalid argument supplied for foreach() in /var/www/whmcs/includes/functions.php on line 0, referer: https://domain.com/cart.php?a=checkout
[Wed Jan 20 14:05:50 2016] [error] [client x.x.x.x] PHP Stack trace:, referer: https://domain.com/cart.php?a=checkout
[Wed Jan 20 14:05:50 2016] [error] [client x.x.x.x] PHP   1. call_user_func() /var/www/whmcs/includes/classes/WHMCS/Module/AbstractModule.php:0, referer: https://domain.com/cart.php?a=checkout
[Wed Jan 20 14:05:50 2016] [error] [client x.x.x.x] PHP   2. ispcfg3_CreateAccount() /var/www/whmcs/includes/classes/WHMCS/Module/AbstractModule.php:0, referer: https://domain.com/cart.php?a=checkout

**Comment by cwispy** [comment]
Did you resolve your issue?
