### ISSUE TITLE
Error: SOAP Error: Could not connect to host

### ISSUE THREAD

**Issue by agentmoller001** [cwispy/ispcfg3#12]
Can you please help me? I keep getting -

Module Create Failed - Service ID: 6 - Error: SOAP Error: Could not connect to host

What am I doing wrong?

**Comment by agentmoller001** [comment]
I found the problem. The IP was not the same as the servers main IP. But, once I got it correct, it crashed the server it was trying to modify.

**Comment by agentmoller001** [comment]
Same problem again

> Error: SOAP Error: Could not connect to host

Is this a known issue? I have tried everything. Please help.

**Comment by agentmoller001** [comment]
Hello??

**Comment by agentmoller001** [comment]
...

**Comment by agentmoller001** [comment]
17 days and no answer. This must not work anymore and not being maintained. Anyone capable of using this still?

**Comment by cwispy** [comment]
Just because there is no response it does not mean it is not being maintained. I released this as open source so others can see the code and if need be fix issues themselves. If you cant get it working maybe try the http://www.howtoforge.com/forums/showthread.php?p=322692 thread.

**Comment by agentmoller001** [comment]
Thanks for the help.
