### ISSUE TITLE
with ISPConfig 3.1

### ISSUE THREAD

**Issue by jasoriano** [cwispy/ispcfg3#14]
when customers are created works, but does not work when you suspend or terminate accounts.
return this error: SOAP Error: Could not connect to host

**Comment by backilein** [comment]
Check your ssl

**Comment by jasoriano** [comment]
My SSL its ok.

**Comment by backilein** [comment]
I use letsencrypt

**Comment by jasoriano** [comment]
I use a Comodo PositiveSSL Wildcard in all servers.

**Comment by backilein** [comment]
i test later on other server

**Comment by backilein** [comment]
you can test to change all          /* Connect to SOAP Server */

to:
        /* Connect to SOAP Server */
        $client = new SoapClient( null, 
                            array( 'location' => $soap_url,
                                    'uri' => $soap_uri,
                                    'exceptions' => 1,
                                    'stream_context'=> stream_context_create(
                                            array('ssl'=> array(
                                                'verify_peer'=>false,
                                                'verify_peer_name'=>false))
                                            ),
                                        'trace' => false
                                    )
                                );

**Comment by jasoriano** [comment]
Works!!

Thx u!!

**Comment by cwispy** [comment]
Looks like I was half asleep when I added the SOAP connection fix before and only added it to the add function. I have just updated the file again adding the fix to all functions.
