### ISSUE TITLE
DNS zone not created

### ISSUE THREAD

**Issue by romlaum** [cwispy/ispcfg3#15]
Hello

I've a problem with this module. It dosn't create DNS zones. All is ok except DNS ?
In debug mode I found 

```
Array
(
    [server_id] => 
    [zone] => 
    [name] => www
    [type] => CNAME
    [data] => domain.com.
    [aux] => 0
    [ttl] => 3600
    [active] => y
    [stamp] => 2016-10-01 14:34:16
    [serial] => 
)
```

It this normal that server_id/zone & serial are empty ?

thanks

**Comment by cwispy** [comment]
Do you have your DNS server listed in the WHMCS server group?

**Comment by romlaum** [comment]
You mean in WHMCS server configuration page (/configservers.php?action=manage&id=X) ? Yes two DNS are registrered.

**Comment by cwispy** [comment]
Yes, but have you also added them to the server group that you are using on the whmcs product?

**Comment by romlaum** [comment]
I'm not sure to understand sorry. 

iscfg is installed on two servers (host1 & host2 : master and slave (dns1 & dns2)). Only host1 is registered in WHMCS. 
In host1 config DNS are ok (host & IP). 
I can't find any other place to save DNS ? host1 is already saved in group used by ispcfg products. 

In module DNS config there is :
host1.domain.xxx,host2.domain.xxx,info,1,121.121.121.121 (wich is host1 IP)

**Comment by cwispy** [comment]
See the wiki, in particular the part about the servers, WHMCS Add Servers and WHMCS Server Group. Every server which is going to have services, needs to be in the server group on whmcs.

**Comment by romlaum** [comment]
Ok thank you. Very strange because all works fine (FTP user, website creation etc), but juste DNS zone remains empty. If I create it manually all services comes up right now.

And when I delete user account from ispcfg I see this warning : 
dns_rr(3), ftp_user(1), mail_domain(1), web_domain(1), domain(1),
A , CNAME & MX are correctly registered in ispcfg database

**Comment by cwispy** [comment]
The DNS Template you reference in WHMCS should have something like this in it.

[ZONE]
origin={DOMAIN}.
ns={NS1}.
mbox={EMAIL}.
refresh=7200
retry=600
expire=1209600
minimum=86400
ttl=3600

[DNS_RECORDS]
NS|{DOMAIN}.|{NS1}.|0|3600
NS|{DOMAIN}.|{NS2}.|0|3600

**Comment by romlaum** [comment]
Thank yes yes it seems the default model.
Last question :) I'm looking in debug page from WHMCS, and at "creatednszone" answer is juste "DNS Template 1", nothing else (no formating.) is this a normal answer ?

**Comment by romlaum** [comment]
Hi

After some research I found this problem already exists [here](https://www.howtoforge.com/community/threads/new-ispconfig-module-for-whmcs.67824/page-12#post-334326) and [here](https://www.howtoforge.com/community/threads/ispconfig-ispcfg3-module-error.71768/) 
I tried multiples reinstallations (in my openstack cluster) with debian and centos and WHMCS (last releases) and this problem happen again. Please contact me in PM, I absolutely need this module. Thanks.

**Comment by cwispy** [comment]
> I'm looking in debug page from WHMCS, and at "creatednszone" answer is juste "DNS Template 1", nothing else (no formating.) is this a normal answer ?

Yes that is correct. You should have other dns debug such as creatednsa, creatednscname, creatednsmx and createmaildomain in your logs too.

**Comment by Ho2x** [comment]
Hello,
I have exactly the same problem with the same config.
Have you finally found a solution?

Thank you

**Comment by cwispy** [comment]
This bug was only affecting users of Bind. Are you also using Bind Ho2x?

**Comment by Ho2x** [comment]
Yes using bind ...

**Comment by Ho2x** [comment]
If you have a solution to bind I am interested!
Thank you for your GIT!

**Comment by thegr33nhornet** [comment]
any update on this?? also not creating the DNS zone, using BIND also.

**Comment by cwispy** [comment]
Looks like the issue is in ISPConfig. You need to add xfer= x.x.x.x to your dns template, or if you prefer, run the below mysql command against your ispconfig database.

ALTER TABLE `dns_soa`
CHANGE COLUMN `xfer` `xfer` VARCHAR(255) NULL DEFAULT NULL AFTER `active`;
