### ISSUE TITLE
On creating new Website please allow for IPv4 and IPv6 selection

### ISSUE THREAD

**Issue by petzsch** [cwispy/ispcfg3#16]
Currently new Websites are created with IPv4 beeing * and IPv6 beeing blank. I'd like to be able to choose the IP for a new website. Perhaps make that an option in the product setup page?

Thx for the great peace of software!

**Comment by cwispy** [comment]
Hi petzsch,

I have been looking at how I could do this as its something that many would like to have. I am trying to work out how I should handle the IP addresses. Obviously there needs to be some checks put in place to prevent totally random IP addresses being used, but there also needs to be some way of tracking IP's which have been used already. So at this stage I am open to any suggestions on how to handle this.
