### ISSUE TITLE
WHMCS not creating anything, just sits there at "working"

### ISSUE THREAD

**Issue by rockinprogramerdude** [cwispy/ispcfg3#19]
WHMCS isn't creating the users, it's just sitting at a message "Working" once the "create" button is clicked in the Admin Area.

Using WHMCS 7.

> 03/28/2017 20:34	ispconfig3	createclient	
> 
> Array
> (
>     [whmcsVersion] => 7.0.1-release.1
>     [accountid] => 49
>     [serviceid] => 49
>     [userid] => 1
>     [domain] => ispconfig-demo7.com
>     [username] => demouser
>     [password] => 31gz8V0xdS
>     [packageid] => 18
>     [pid] => 18
>     [serverid] => 13
>     [status] => Active
>     [type] => hostingaccount
>     [producttype] => hostingaccount
>     [moduletype] => ispconfig3
>     [configoption1] =>** omitted **
>     [configoption2] => ** omitted **
>     [configoption3] => ** omitted **
>     [configoption4] => on
>     [configoption5] => 1
>     [configoption6] => jailkit
>     [configoption7] => on
>     [configoption8] => no
>     [configoption9] => on
>     [configoption10] => on
>     [configoption11] => on
>     [configoption12] => on
>     [configoption13] => 0
>     [configoption14] => on
>     [configoption15] => www
>     [configoption16] => on
>     [configoption17] => on
>     [configoption18] => on
>     [configoption19] => on
>     [configoption20] => on
>     [configoption21] => on
>     [configoption22] => on
>     [configoption23] => 3.1
>     [configoption24] => 
>     [customfields] => Array
>         (
>         )
> 
>     [configoptions] => Array
>         (
>         )
> 
>     [clientsdetails] => Array
>         (
>             [userid] => ** omitted **
>             [id] => ** omitted **
>             [uuid] => ** omitted **
>             [firstname] => ** omitted **
>             [lastname] => ** omitted **
>             [fullname] => ** omitted **
>             [companyname] => Punk Media
>             [email] => ** omitted **
>             [address1] => ** omitted **
>             [address2] => ** omitted **
>             [city] => ** omitted **
>             [fullstate] => ** omitted **
>             [state] => ** omitted **
>             [postcode] => ** omitted **
>             [countrycode] => ** omitted **
>             [country] => ** omitted **
>             [phonenumber] => ** omitted **
>             [password] => ** omitted **
>             [statecode] => ** omitted **
>             [countryname] => United States
>             [phonecc] => 1
>             [phonenumberformatted] => ** omitted **
>             [billingcid] => 0
>             [notes] => 
>             [twofaenabled] => 
>             [currency] => 1
>             [defaultgateway] => paypalexpress
>             [cctype] => 
>             [cclastfour] => 
>             [securityqid] => 1
>             [securityqans] => ** omitted **
>             [groupid] => 0
>             [status] => Active
>             [credit] => 6000.00
>             [taxexempt] => 
>             [latefeeoveride] => 1
>             [overideduenotices] => 1
>             [separateinvoices] => 
>             [disableautocc] => 1
>             [emailoptout] => 
>             [overrideautoclose] => 1
>             [allowSingleSignOn] => 1
>             [language] => english
>             [lastlogin] => ** omitted **
>             [customfields1] => 
>             [customfields] => Array
>                 (
>                     [0] => Array
>                         (
>                             [id] => 1
>                             [value] => 
>                         )
> 
>                     [1] => Array
>                         (
>                             [id] => 2
>                             [value] => ** omitted **
>                         )
> 
>                     [2] => Array
>                         (
>                             [id] => 3
>                             [value] => ** omitted **
>                         )
> 
>                     [3] => Array
>                         (
>                             [id] => 4
>                             [value] => Default
>                         )
> 
>                     [4] => Array
>                         (
>                             [id] => 20
>                             [value] => 
>                         )
> 
>                     [5] => Array
>                         (
>                             [id] => 21
>                             [value] => 
>                         )
> 
>                     [6] => Array
>                         (
>                             [id] => 22
>                             [value] => 
>                         )
> 
>                     [7] => Array
>                         (
>                             [id] => 23
>                             [value] => 
>                         )
> 
>                     [8] => Array
>                         (
>                             [id] => 24
>                             [value] => 
>                         )
> 
>                     [9] => Array
>                         (
>                             [id] => 25
>                             [value] => 
>                         )
> 
>                     [10] => Array
>                         (
>                             [id] => 29
>                             [value] => 
>                         )
> 
>                 )
> 
>             [customfields2] => ** omitted **
>             [customfields3] => ** omitted **
>             [customfields4] =>** omitted **
>             [customfields5] => 
>             [customfields6] => 
>             [customfields7] => 
>             [customfields8] => 
>             [customfields9] => 
>             [customfields10] => 
>             [customfields11] => 
>         )
> 
>     [server] => 1
>     [serverip] => ** omitted **
>     [serverhostname] => ** omitted **
>     [serverusername] => ** omitted **
>     [serverpassword] => ** omitted **
>     [serveraccesshash] => 
>     [serversecure] => 
>     [serverhttpprefix] => http
>     [serverport] => 
>     [action] => create
> )
> 
>

**Comment by rockinprogramerdude** [comment]
Can I get a bump please?

**Comment by cwispy** [comment]
I could not even begin to guess. Have you followed the setup procedure for the ISPConfig site of things? Sounds like its not connecting to your ispconfig instance.

**Comment by geniuskidkanyi** [comment]
followed tutorial and getting 500 error. this same info on logs

**Comment by cwispy** [comment]
A 500 error is coming from your web server. It has nothing to do with the module.
