### ISSUE TITLE
WHMCS 7.2 cant add server

### ISSUE THREAD

**Issue by djsmiley05** [cwispy/ispcfg3#20]
Hi there,

At first, thank you for the module.

I was trying to setup your module under WHMCS 7.2, but if the modules is installed, then i cant create servers or products.
WHMCS displaying an OOps error, here is the apache log about that error:
[Thu May 25 12:06:56.180054 2017] [proxy_fcgi:error] [pid 27073] [client *:47301] AH01071: Got error 'PHP message: [WHMCS Application] ERROR: exception 'Whoops\\Exception\\ErrorException' with message 'in_array() expects parameter 2 to be array, null given'
in /srv/www/clients/client1/web170/web/admin/configservers.php:0 Stack trace: #0 /srv/www/clients/client1/web170/web/admin/configservers.php(0): Whoops\\Run->handleError(2, 'in_array() expe...', '/srv/www/client...', 0, Array) #1 {main} {"exception":"[object] (Whoops\\\
\Exception\\\\ErrorException(code: 2): in_array() expects parameter 2 to be array, null given at /srv/www/clients/client1/web170/web/admin/configservers.php:0)"} []\n', referer: https://admin.x/admin/configservers.php

Can you help me about that?
Is your module compatible with WHMCS 7.2?

Thank you!

Regards,
Zoltan

**Comment by cwispy** [comment]
Yes the module is compatible with WHMCS 7.2. I am running it on 7.2.1 currently. Sorry I have no idea about the log message above. You could turn on module logs in whmcs from utilities, log, module log. My best guess would be that you have missed part of the setup by not adding a server into the server group of the product in whmcs.

**Comment by djsmiley05** [comment]
Hi,
I've figured it out.
If you comments the first line like:
`//ini_set('error_reporting', E_ALL & ~E_NOTICE);`
Then its working like a charm. So again, thank you for the development.

Off question: i saw the another branch with templates, etc. Do you planning some kind of domain management trough your module?
