### ISSUE TITLE
WHMCS 7.2.3

### ISSUE THREAD

**Issue by mj-bsdops** [cwispy/ispcfg3#23]
Hello. 
I've tried run yours module under WHMCS 7.2.3
After create a directory  in modules/servers/ipscfg3 and uploading file ispcfg3.php I can't chose server type ipscfg3 (server details in tab servers). It isn't on the list. 

Do you have maybe information about compatibility with whmcs 7.2.3 or maybe I'm doing something wrong?

Thanks in advance. 
/BR
Michał

**Comment by cwispy** [comment]
I run it under 7.3.0-release.1 with no issues. check your spelling, in this ticket you spelt the directory name wrong. If the folder does not match the name of the file, it will not show up in whmcs.

**Comment by mj-bsdops** [comment]
You are right! That was my fault. Thanks a lot for answer.
