### ISSUE TITLE
Added database creation BUG

### ISSUE THREAD

**Issue by Ho2x** [cwispy/ispcfg3#25]
Hello,
Your establishment of database creation is not working properly.

I put you screen for more ease.

Thank you

![1](https://user-images.githubusercontent.com/23018181/32626309-3a1df452-c58f-11e7-9a2e-38337d74eaf9.png)
![2](https://user-images.githubusercontent.com/23018181/32626323-4365c4e0-c58f-11e7-85ec-08d0dccc169a.png)
![3](https://user-images.githubusercontent.com/23018181/32626376-6d49e43a-c58f-11e7-8322-7c9cf1e80090.png)

**Comment by cwispy** [comment]
Its not finished at the moment. I am still completing the code.
