### ISSUE TITLE
FileManager Bug Report

### ISSUE THREAD

**Issue by Ho2x** [cwispy/ispcfg3#27]
Hi,

Since the last update I have a problem with the web ftp.

That comes from my side or the plugin?

Thank you for your time !

![capture](https://user-images.githubusercontent.com/23018181/33415265-acb21726-d595-11e7-9440-7d9837e75798.PNG)

**Comment by cwispy** [comment]
Can your whmcs resolve the server / account it is trying to access?

**Comment by ARISTheGod** [comment]
I have the same problem
