### ISSUE TITLE
PHP disabled by default on site creation

### ISSUE THREAD

**Issue by thegr33nhornet** [cwispy/ispcfg3#28]
PHP seems to be disabled by default on site creation

**Comment by thegr33nhornet** [comment]
Fixed this by adding
'php'	=> 'PHP-FPM',
to the $webcreation params, can I also change the php version? I've tried with no luck.

**Comment by cwispy** [comment]
Issue was confirmed and fixed in commit 
https://github.com/cwispy/ispcfg3/commit/bc4a14335d297be7cfa4cd0e3d80e44e68161dcf

This commit uses the first enabled php type that it gets from the limit template.

**Comment by thegr33nhornet** [comment]
Great stuff :)
Is it possible to set the PHP version? (5.6/7.0)

**Comment by cwispy** [comment]
Im not aware of a way of changing the php version from the api. Would have to look through the ispconfig code to see if its supported.

**Comment by thegr33nhornet** [comment]
I think someone implemented it on a fork of your module ?
https://github.com/boldbesusiax/whmcs-ispconfig3

I'm not sure though, not tested.

**Comment by cwispy** [comment]
There is no field called php_version, only the fastcgi_php_version.

That fork is using hard set local settings which I have been trying hard to get away from. Though it does show that there is php version api calls which I had not looked at before.
