### ISSUE TITLE
Errors when updating website via client area

### ISSUE THREAD

**Issue by thegr33nhornet** [cwispy/ispcfg3#29]
When I update websites via the client area I get a success message but also an internal server error?

The changes do seem to go through.

![1](https://user-images.githubusercontent.com/22370877/36901147-f742fb54-1e1d-11e8-8ed5-527f9f919f7d.png)
![2](https://user-images.githubusercontent.com/22370877/36901150-fb235bec-1e1d-11e8-8d4f-b11113549c52.png)
![3](https://user-images.githubusercontent.com/22370877/36901151-fc9b390e-1e1d-11e8-82de-54dab782f841.png)

As I said the changes do seem to go through to ispconfig fine.

Great work on this module cwispy, do you accept donations?

**Comment by cwispy** [comment]
I cant replicate this issue.

**Comment by thegr33nhornet** [comment]
Must be an issue on my side

**Comment by thegr33nhornet** [comment]
This only happens when I use whmcs on a different server/domain.
Have tried setting headers with no luck, either way the changes do actually go through to ISPConfig.

Any idea what I could do?

**Comment by cwispy** [comment]
What do you mean by use it on a different server/domain?
