### ISSUE TITLE
FTP account 'quota_size' 

### ISSUE THREAD

**Issue by jozsefhabit** [cwispy/ispcfg3#32]
Hello,
it seems to me, that ftp account quota size should be $tmpl['limit_web_quota'] instead of $tmpl['limit_web_domain']
https://github.com/cwispy/ispcfg3/blob/bc4a14335d297be7cfa4cd0e3d80e44e68161dcf/ispcfg3.php#L561
What dou you think?
Br.

**Comment by cwispy** [comment]
Thanks for reporting this. I have just fixed it.
https://github.com/cwispy/ispcfg3/commit/707db03cfe4372dadd464be8d1d313c1547adf78
