### ISSUE TITLE
error adding dns a record

### ISSUE THREAD

**Issue by aheinzel** [cwispy/ispcfg3#36]
Hi,
when using ispcfg3 with ISPConfig Version: 3.1.13 adding a dns a record fails with the following error:

```Incorrect datetime value: '' for column 'stamp' at row 1 INSERT INTO `dns_rr` (`server_id`, `zone`, `name`, `type`, `data`, `ttl`, `active`, `stamp`, `serial`, `sys_userid`, `sys_groupid`, `sys_perm_user`, `sys_perm_group`, `sys_perm_other`) VALUES ('1', '9', 'xxx.yyy.com.', 'a', 'xxx.xxx.xxx.xxx', '86400', 'y', '', '0', '8', '8', 'riud', 'riud', '')```

The problem is that the value for the database field stamp is not set automatically when using the ISPConfig remote API. The ISPConfig dns form template (ispconfig/interface/web/dns/form/dns_a.tform.php) defines the field stamp with an empty string as default value.
```
'stamp' => array (
    'datatype' => 'VARCHAR',
    'formtype' => 'TEXT',
    'default' => '',
    'value'  => '',
    'width'  => '30',
    'maxlength' => '255'
    ),
```

When adding a dns a record via the ISPConfig webinterface serial and stamp are automatically set before the new dns a record is written to the table dns_rr (ispconfig/interface/web/dns/dns_edit_base.php).
```
$soa = $app->db->queryOneRecord("SELECT serial FROM dns_rr WHERE id = ?", $this->id);
$this->dataRecord["serial"] = $app->validate_dns->increase_serial($soa["serial"]);
$this->dataRecord["stamp"] = date('Y-m-d H:i:s');
```

However, in the remoting API only the serial number is automatically increased if update_serial is set to true. In consequence the default value for stamp (empty string) is passed to the database (ispconfig/interface/lib/classes/remote.d/dns.inc.php).
```    
if($update_serial) $this->increase_serial($session_id, $client_id, $params);
return $this->insertQuery('../dns/form/dns_a.tform.php', $client_id, $params);
```

Therefore, the timestamp value for stamp must be passed to ISPConfig in the remote call. An easy fix is to include stamp with the current date/time in the options array before executing the soap request.
```
--- dns.php.bak	2019-02-23 06:14:24.287829034 +0100
+++ dns.php	2019-02-23 06:11:25.103768432 +0100
@@ -39,6 +39,7 @@
             'type' => $_REQUEST['type'],
             'data' => $_REQUEST['destination'],
             'ttl' => $_REQUEST['ttl'],
+            'stamp' => date('Y-m-d H:i:s'),
             'active' => 'y',
             'ihost_dns_function' => 'dns_'.$_REQUEST['type'].'_add',
         );
```

**Comment by cwispy** [comment]
You appear to be reporting an error with ISPConfig to the plugin. However upon checking the database, the 'stamp' field in the database is ser to 'CURRENT_TIMESTAMP' so no value is required to be passed to it. If your table is missing that, you may have missed a table upgrade somewhere along the line.

**Comment by matahr** [comment]
I have the same response "Incorrect datetime value: '' for column 'stamp' at row 1 INSERT INTO `dns_rr`" 

Stamp is set to 'CURRENT_TIMESTAMP' but I get the same error as described here
