### ISSUE TITLE
Change text web ftp bug

### ISSUE THREAD

**Issue by Ho2x** [cwispy/ispcfg3#37]
Hello,

I have a problem, when I want to create a file (ex: test.php) with code inside, when saving it transforms all my code ...

Example
<! DOCTYPE html PUBLIC "- // W3C // DTD XHTML 1.0 Strict // EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

becomes:

& lt;! DOCTYPE html & gt;
& Lt; html & gt;
    & Lt; head & gt;
        & lt; title & gt; This is a test page with PHP tags & lt; / title & gt;
        & lt; meta charset = & quot; utf-8 & quot; / & Gt;

**Comment by cwispy** [comment]
You will need to contact the makers of the plugin https://github.com/Studio-42/elFinder as we only include it in the package. It is not maintained by us.

**Comment by Ho2x** [comment]
The installed version is outdated and has a lot of problems

**Comment by Ho2x** [comment]
According to the developers the problem comes from your script.

https://github.com/Studio-42/elFinder/issues/2887

Thank you
