### ISSUE TITLE
A client with multiple domains, module not working

### ISSUE THREAD

**Issue by francois007** [cwispy/ispcfg3#4]
Hi,
I point out this problem. The form must be in error if I try to assign a client to another hosting space.
The message is the following:

Order Accept Encountered Problems
SOAP Error: customer_no_error_unique<br /> 
Invalid value "" for parameter "registrant_dotitnationality"!

**Comment by cwispy** [comment]
Hi,
What do you mean by assign a client to another hosting space?

**Comment by francois007** [comment]
I explained in detail: on a server run by the ISPConfig module assigns a customer account number, when the same customer must assign a different hosting service module goes wrong. The error is determined by the account number previously assigned to the same customer by the module itself.

I modified the ispcfg3.php at line 366 in this way:
'customer_no' => '',

I deleted the account number to all customers on ISPConfig to avoid the same mistake, if a customer purchases another hosting service.

Now the module no longer generates this error and allows me to assign multiple services to the same customer. One note, each hosting service that creates, generates a duplicate of the customer in the customers section of ISPConfig.

**Comment by cwispy** [comment]
Are you sure you have the most current version of the module installed? Initially I was using the customer ID field there, but I changed to using the product ID a long time ago, which got rid of the error your referring to. The module is designed to create a new ISPConfig user for every product under the user. It will not create one user and then create multiple products under that user. You might want to refer to the thread on HowtoForge where a lot of this has already been covered.

https://www.howtoforge.com/community/threads/new-ispconfig-module-for-whmcs.67824/

**Comment by francois007** [comment]
I'm pretty sure you have the latest version of the module ispcfg3, yesterday I checked again here if there were any updates in the last days.
Now I take a look at the thread on HowtoForge, thanks for the answer.
