### ISSUE TITLE
SOAP Error: Could not connect to host

### ISSUE THREAD

**Issue by kayyyy** [cwispy/ispcfg3#5]
Hi,

great module!
But for me it`s not working.

I am getting the above error.
But the ISPConfig URL and the API user is correct. What else could be the problem?

**Comment by kayyyy** [comment]
Ah i entered the url with https. Now it works awesome!

**Comment by francois007** [comment]
I have the same problem and I can not solve it

**Comment by cwispy** [comment]
Enter the server url without the http:// or https:// and if you need to use a port, then use 1.2.3.4:8080 for example.

**Comment by francois007** [comment]
Order Accept Encountered Problems
SOAP Error: Could not connect to host

I tried them all, IP: port, URL: port, http or https...
I feel pretty frustrated...

**Comment by cwispy** [comment]
In your case, it sounds like a firewall issue. Can you connect to the ISPConfig web interface from the WHMCS server?
