### ISSUE TITLE
All work, but no database is created.

### ISSUE THREAD

**Issue by sandro-saperfare** [cwispy/ispcfg3#8]
Looks like an amazing piece of work.
I'm using it ispcf3 with the last version of ISPConfig 3.0.5 and WHMCS 6.1.1. All work fine, but no DB is currently created, it's normal?
Thanks in advance,
Best regards.

Sandro

**Comment by cwispy** [comment]
Yes it does work with 6.1.1. We are using it with 6.1.1 ourselves. The module does not automatically create the database.

**Comment by sandro-saperfare** [comment]
Hi cwispy, thanks for the response. Do you think is possibile, in future, to have the possibility to implement also the DB creation?
